using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Petal.Framework.Persistence;

[JsonSourceGenerationOptions(WriteIndented = true)]

[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(float))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(NamespacedString))]
[JsonSerializable(typeof(JsonManifest))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(List<bool>))]
[JsonSerializable(typeof(List<int>))]
[JsonSerializable(typeof(List<long>))]
[JsonSerializable(typeof(List<float>))]
[JsonSerializable(typeof(List<double>))]
[JsonSerializable(typeof(List<object>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<NamespacedString>))]
[JsonSerializable(typeof(List<JsonManifest>))]
[JsonSerializable(typeof(List<JsonElement>))]
[JsonSerializable(typeof(HashSet<bool>))]
[JsonSerializable(typeof(HashSet<int>))]
[JsonSerializable(typeof(HashSet<long>))]
[JsonSerializable(typeof(HashSet<float>))]
[JsonSerializable(typeof(HashSet<double>))]
[JsonSerializable(typeof(HashSet<object>))]
[JsonSerializable(typeof(HashSet<string>))]
[JsonSerializable(typeof(HashSet<NamespacedString>))]
[JsonSerializable(typeof(HashSet<JsonManifest>))]
[JsonSerializable(typeof(HashSet<JsonElement>))]
[JsonSerializable(typeof(Dictionary<bool, bool>))]
[JsonSerializable(typeof(Dictionary<bool, int>))]
[JsonSerializable(typeof(Dictionary<bool, long>))]
[JsonSerializable(typeof(Dictionary<bool, float>))]
[JsonSerializable(typeof(Dictionary<bool, double>))]
[JsonSerializable(typeof(Dictionary<bool, object>))]
[JsonSerializable(typeof(Dictionary<bool, string>))]
[JsonSerializable(typeof(Dictionary<bool, NamespacedString>))]
[JsonSerializable(typeof(Dictionary<bool, JsonManifest>))]
[JsonSerializable(typeof(Dictionary<bool, JsonElement>))]
[JsonSerializable(typeof(Dictionary<int, bool>))]
[JsonSerializable(typeof(Dictionary<int, int>))]
[JsonSerializable(typeof(Dictionary<int, long>))]
[JsonSerializable(typeof(Dictionary<int, float>))]
[JsonSerializable(typeof(Dictionary<int, double>))]
[JsonSerializable(typeof(Dictionary<int, object>))]
[JsonSerializable(typeof(Dictionary<int, string>))]
[JsonSerializable(typeof(Dictionary<int, NamespacedString>))]
[JsonSerializable(typeof(Dictionary<int, JsonManifest>))]
[JsonSerializable(typeof(Dictionary<int, JsonElement>))]
[JsonSerializable(typeof(Dictionary<long, bool>))]
[JsonSerializable(typeof(Dictionary<long, int>))]
[JsonSerializable(typeof(Dictionary<long, long>))]
[JsonSerializable(typeof(Dictionary<long, float>))]
[JsonSerializable(typeof(Dictionary<long, double>))]
[JsonSerializable(typeof(Dictionary<long, object>))]
[JsonSerializable(typeof(Dictionary<long, string>))]
[JsonSerializable(typeof(Dictionary<long, NamespacedString>))]
[JsonSerializable(typeof(Dictionary<long, JsonManifest>))]
[JsonSerializable(typeof(Dictionary<long, JsonElement>))]
[JsonSerializable(typeof(Dictionary<float, bool>))]
[JsonSerializable(typeof(Dictionary<float, int>))]
[JsonSerializable(typeof(Dictionary<float, long>))]
[JsonSerializable(typeof(Dictionary<float, float>))]
[JsonSerializable(typeof(Dictionary<float, double>))]
[JsonSerializable(typeof(Dictionary<float, object>))]
[JsonSerializable(typeof(Dictionary<float, string>))]
[JsonSerializable(typeof(Dictionary<float, NamespacedString>))]
[JsonSerializable(typeof(Dictionary<float, JsonManifest>))]
[JsonSerializable(typeof(Dictionary<float, JsonElement>))]
[JsonSerializable(typeof(Dictionary<double, bool>))]
[JsonSerializable(typeof(Dictionary<double, int>))]
[JsonSerializable(typeof(Dictionary<double, long>))]
[JsonSerializable(typeof(Dictionary<double, float>))]
[JsonSerializable(typeof(Dictionary<double, double>))]
[JsonSerializable(typeof(Dictionary<double, object>))]
[JsonSerializable(typeof(Dictionary<double, string>))]
[JsonSerializable(typeof(Dictionary<double, NamespacedString>))]
[JsonSerializable(typeof(Dictionary<double, JsonManifest>))]
[JsonSerializable(typeof(Dictionary<double, JsonElement>))]
[JsonSerializable(typeof(Dictionary<object, bool>))]
[JsonSerializable(typeof(Dictionary<object, int>))]
[JsonSerializable(typeof(Dictionary<object, long>))]
[JsonSerializable(typeof(Dictionary<object, float>))]
[JsonSerializable(typeof(Dictionary<object, double>))]
[JsonSerializable(typeof(Dictionary<object, object>))]
[JsonSerializable(typeof(Dictionary<object, string>))]
[JsonSerializable(typeof(Dictionary<object, NamespacedString>))]
[JsonSerializable(typeof(Dictionary<object, JsonManifest>))]
[JsonSerializable(typeof(Dictionary<object, JsonElement>))]
[JsonSerializable(typeof(Dictionary<string, bool>))]
[JsonSerializable(typeof(Dictionary<string, int>))]
[JsonSerializable(typeof(Dictionary<string, long>))]
[JsonSerializable(typeof(Dictionary<string, float>))]
[JsonSerializable(typeof(Dictionary<string, double>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, NamespacedString>))]
[JsonSerializable(typeof(Dictionary<string, JsonManifest>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(Dictionary<NamespacedString, bool>))]
[JsonSerializable(typeof(Dictionary<NamespacedString, int>))]
[JsonSerializable(typeof(Dictionary<NamespacedString, long>))]
[JsonSerializable(typeof(Dictionary<NamespacedString, float>))]
[JsonSerializable(typeof(Dictionary<NamespacedString, double>))]
[JsonSerializable(typeof(Dictionary<NamespacedString, object>))]
[JsonSerializable(typeof(Dictionary<NamespacedString, string>))]
[JsonSerializable(typeof(Dictionary<NamespacedString, NamespacedString>))]
[JsonSerializable(typeof(Dictionary<NamespacedString, JsonManifest>))]
[JsonSerializable(typeof(Dictionary<NamespacedString, JsonElement>))]
public partial class DefaultJsonTypeInfo : JsonSerializerContext
{

}